### ISSUE TITLE
The question about evaluation metric

### ISSUE THREAD

**Issue by fangfchen** [doubledaibo/drnet_cvpr2017#15]
您好，我最近看了您的文章（及代码）和之前李飞飞团队的文章（及代码），对你们的评价标准（特别是任务1——只预测predicate）有一些困惑。主要是针对Ground Truth中有些object pair可能出现多种predicate的情况，比如在图片“8207112087_d049d707d2_b.jpg”中Ground Truth同时包含"person has surfboard","person hold surfboard","person carry surfboard"。假设该图片只有这3个关系，下面将会以此为例，提出我们的问题。
[8207112087_d049d707d2_b.jpg](https://github.com/fangfchen/drnet_cvpr2017/blob/master/TempImage/8207112087_d049d707d2_b.jpg)

根据李飞飞团队的文章，它们对任务1的结果的评价方法是，从Ground Truth中依次取出relationship的object pair，对其predicate进行预测，如果top1结果与Ground Truth相同即算对，否则算错。对于上述图片例子，他们对<person,surfboard> pair预测出的prediate是hold，且预测三次应该都是hold（如图是其公布代码的预测数据，其中1代表person，80代表surfboard，28代表hold），故其recall=1/3.
基于此评价标准，他们的recall@50 = recall@100.
[预测结果](https://github.com/fangfchen/drnet_cvpr2017/blob/master/TempImage/result.png)

继而我也研读了您的文章和代码，但是没有找到任务1的评价代码，所以只能从任务2、3的代码中推测您的做法。我猜测，你们的评价方法是，对Ground Truth中的所有object pair预测predicate，同时保存预测出的relationship和其对应的score(即置信度)，对图片中所有预测出的relationship按score进行排序，取前50/100个（如果不足50/100则取Ground Truth数量），计算有多少出现在Ground Truth中。对于上述图片的例子，假如预测出"person has surfboard" 0.91,"person hold surfboard" 0.89,"person beside surfboard" 0.72，则其中有2个是对的，故recall=2/3.

不知道我的理解是否正确，如果不正确，希望您可以告诉我您对任务1的评价具体是怎么做的，十分感谢！

**Comment by doubledaibo** [comment]
Hi,  I didn't use the assumption that each pair has only one predicate. So if I have N objects detected, I will compute the recalls among (N - 1) * N * k predictions, where k is the number of predicate classes.

**Comment by fangfchen** [comment]
谢谢您的回复。基于此，我还有两个困惑。

1.注意到您的文中也对李飞飞的方法在两个数据集上做了实验，请问在复现李飞飞的方法时，计算recall的方法也是这样的么（ 即考虑一组pair可能包含多种predicates的情况，在(N - 1) * N * k 种可能预测中算recall）？

2.当一个图片中Ground Truth数量>50时，计算recall@50的分母取50还是Ground Truth数量（即"前50个的预测中正确的数量/50"，还是"前50个的预测中正确的数量/Ground Truth数量"）？如果是后者，是不是会存在recall从理论上也无法达到1的情况？

希望可以得到您的解答，不胜感激。

**Comment by doubledaibo** [comment]
Hi, 
   When evaluating their method I followed their assumption to be consistent with their original setting. Also, their prediction contains a term that is a ranking score, which may not comparable between pairs of objects.
   Recall@50 is selecting the top 50 predictions from (N - 1) * N * k.

**Comment by fangfchen** [comment]
谢谢您的回复。最后一个问题，是实验中的一个细节问题。
注意到您在选top 50 predictions 时用了一个"thresh=0.05"进行过滤，即score<0.05的直接舍弃，这一点在您的文章中没有做详细的解释。
我的问题是，这么做是基于方法的考虑（即认为<0.05的predictions是无意义的，认为其并没有检测出实质性的关系），还是基于实验效率的考虑（即为了优化时间复杂度和空间复杂度而做的一个剪枝）？

**Comment by doubledaibo** [comment]
0.05 is just used for computational efficiency. you can remove this threshold.

**Comment by fangfchen** [comment]
好的，非常感谢您的耐心回答~
