### ISSUE TITLE
missing image

### ISSUE THREAD

**Issue by chensonglu** [doubledaibo/drnet_cvpr2017#17]
Can you share this image "sg_dataset/sg_test_images/4392556686_44d71ff5a0_o.jpg" because it's missing. Thank you very much.

**Comment by doubledaibo** [comment]
Hi, 
 You could either replace 4392556686_44d71ff5a0_o.gif with 4392556686_44d71ff5a0_o.jpg or convert the former into the latter.

**Comment by chensonglu** [comment]
@doubledaibo Thank you.

**Comment by chensonglu** [comment]
The missing image is caused by mismatched .mat file and image name. There is one .gif image, but in the .mat file, it's .jpg.
