### ISSUE TITLE
proof of formulation（4）

### ISSUE THREAD

**Issue by chensonglu** [doubledaibo/drnet_cvpr2017#18]
Hi，how can i get the supplementary material of the proof of formulation（4). Thank you.

**Comment by Shane-Josias** [comment]
Hi Bo Dai, 

I am also wondering whether you could make the supplemental material available please? I can't seem to find it at the CVPR proceedings. 

Regards
Shane

**Comment by doubledaibo** [comment]
Hi,
   It's available on my personal website.

**Comment by Shane-Josias** [comment]
Thanks Bo Dai, I've found it!
