### ISSUE TITLE
The number of images on sVG dataset

### ISSUE THREAD

**Issue by GriffinLiang** [doubledaibo/drnet_cvpr2017#7]
Recently, I downloaded the [**sVG dataset**](https://drive.google.com/file/d/0B5RJWjAhdT04SXRfVHBKZ0dOTzQ/view?usp=sharing) provided by the author. However, there are 67086 images and 8995 images for training and testing respectively. As mentioned in the original paper, the total number of images should be 108K. Which number is correct?

**Comment by doubledaibo** [comment]
I further cleaned the dataset, I think it's better to refer to this released one in your projects.

**Comment by GriffinLiang** [comment]
Got it. Thanks.

**Comment by doubledaibo** [comment]
I think I've used the version 1.0. I removed redundant bounding boxes but didn't move bounding boxes.
