### ISSUE TITLE
Problems about run "test_predicate_recognition.py"

### ISSUE THREAD

**Issue by plutozjc** [doubledaibo/drnet_cvpr2017#9]
I ran the python script "test_predicate_recognition.py", but got the following error. 
I prepare the image_paths and gt files according to the needed format. 
But I am unfamiliar with python wrapper of the caffe and have no ideas whether and how to let caffe find "lib/"?
Do you know how to deal with the following error?
Thank you!

> 
I0209 22:57:07.774577 23180 net.cpp:744] Ignoring source layer data
I0209 22:57:07.774600 23180 net.cpp:744] Ignoring source layer qa_data_0_split
I0209 22:57:07.774606 23180 net.cpp:744] Ignoring source layer qb_data_1_split
I0209 22:57:07.774610 23180 net.cpp:744] Ignoring source layer labels_data_4_split
I0209 22:57:07.850764 23180 net.cpp:744] Ignoring source layer pred_softmax_0_split
I0209 22:57:07.850788 23180 net.cpp:744] Ignoring source layer accuracy
I0209 22:57:07.850793 23180 net.cpp:744] Ignoring source layer accuracy_top5
Called with args:
Namespace(caffemodel='/media/sdb1/zhangjunchao/Relation/drnet_cvpr2017/snapshots/drnet_8units_relu_shareweight.caffemodel', gpu_id=0, gt_file='/media/sdb1/zhangjunchao/Relation/drnet_cvpr2017/tools/gt_test.pkl', image_paths='/media/sdb1/zhangjunchao/Relation/drnet_cvpr2017/tools/image_list_test.json', ncls=101, out='output-1', prototxt='/media/sdb1/zhangjunchao/Relation/drnet_cvpr2017/prototxts/test_drnet_8units_relu_shareweight.prototxt', type=0)
0 / 955
Traceback (most recent call last):
  File "test_predicate_recognition.py", line 187, in <module>
    test_net(net, test_image_paths, args)
  File "test_predicate_recognition.py", line 153, in test_net
    itr_pred_batch = forward_batch(net, ims[_cursor : _end_batch], poses[_cursor : _end_batch], qas[_cursor : _end_batch], qbs[_cursor : _end_batch], args)
  File "test_predicate_recognition.py", line 100, in forward_batch
    net_out = net.forward(**forward_args)
  File "/home/zhangjunchao/workspace/caffe/python/caffe/pycaffe.py", line 123, in _Net_forward
    raise Exception('Input blob arguments do not match net inputs.')
Exception: Input blob arguments do not match net inputs.
>

**Comment by doubledaibo** [comment]
The error states Input blob arguments do not match net inputs. You can check the prototxt about the shape of each input, and check whether you provided inputs with current shapes.

**Comment by seconds7** [comment]
@GH-plutozjc Have you solved the problem? I encounter it, too. And don't know why when checking the code.

**Comment by GH-plutozjc** [comment]
@seconds7 I set the 'input_type=3' and solved this problem.  You can try this.

**Comment by GH-plutozjc** [comment]
@doubledaibo  Thanks a lot. I found I had set inappropriate input_type.  I encounter this error with input_type=0, while this error is gone with input_type=3. But I just haven't figured out in what situation the input_type should be 0, 1, or 3?

**Comment by doubledaibo** [comment]
hi @GH-plutozjc , input types are:
 0: only image
 1: only dual spatial masks
 2: image + dual spatial masks
 3: image + dual spatial masks + object category labels

**Comment by GH-plutozjc** [comment]
Thank you. I run this code with "test_drnet_8units_relu_shareweight.prototxt", which has no input of object category labels, so  I should set input type as 2? I have tried 2, but encountered the same error "Input blob arguments do not match net inputs". Why is that?

**Comment by doubledaibo** [comment]
actually it has object category as input, in the form of indicator vectors, qa and qb.

**Comment by GH-plutozjc** [comment]
I get it, thank you!  @doubledaibo

**Comment by CS4Liu** [comment]
I run the python file like this:
python test_predicate_recognition.py --image_paths image_paths_test_VRD.json --def ../prototxts/drnet_8units_softmax.prototxt --net ../snapshots/drnet_8units_softmax.caffemodel --gt_file gtfile_test_VRD.pkl --input_type 3
But I get the same error.Is there any advice?
